Update fourth iteration
ThundeRatz/trekking-magellan-docs pull request #1
Opened 2017-09-01 20:14 UTC by erickotsuka

Fiquei em dúvida se mencionava especificamente a YOLO, colocando uma referência. Se acham que precisa mudar alguma coisa, falem, por favor.

2017-09-01 20:52 UTC, tiagoshibata approved these changes
Por mim pode citar a YOLO e redes neurais de detecção, acho que fica melhor se der mais detalhes.

2017-09-01 20:52 UTC, tiagoshibata commented on README.md
> +## This is an incomplete version!
Acho que dá pra tirar isso? Talvez colocar um link pro PDF no README.md?

2017-09-01 20:53 UTC, tiagoshibata commented on README.md
> +## This is an incomplete version!
Tirar isso = tirar toda a parte que diz que está incompleta

2017-09-02 01:52 UTC, erickotsuka commented
Acha que seria legal mencionar ROS também?

2017-09-02 13:41 UTC, freitas-renato reviewed
Show, bem completo. Acho que poderia adicionar umas fotos do último Winter pra mostrar as mudanças.

2017-09-12 21:25 UTC, d-nery requested changes

2017-09-12 21:25 UTC, d-nery commented on Project documentation/Project documentation.tex
> +~\cite{All Japan Robot Sumo} and Robo-Magellan~\cite{SRS}. After over 15 years
O nome da competição é International Robot Sumo Tournament, All Japan é a versão só para os japoneses

2017-09-12 21:25 UTC, d-nery commented on Project documentation/Project documentation.tex
> +it got 5th place. It was also used in Summer Challenge III, achieving 2nd place, RoboGames
Falta algo aqui, a frase não faz sentido no final.

2017-09-12 21:54 UTC, tiagoshibata commented on Project documentation/Project documentation.tex
> +it got 5th place. It was also used in Summer Challenge III, achieving 2nd place, RoboGames
Tem mais uma linha em baixo, não sei se você viu.

2017-09-13 20:16 UTC, tiagoshibata commented
Estamos OK pra mergear? @d-nery

2017-09-14 21:13 UTC, d-nery commented
Top

2017-09-14 21:13 UTC, d-nery approved these changes

2017-09-14 21:14 UTC, merged